language: node_js

sudo: false

notifications:
  email:
    on_failure: always
    on_success: change

node_js:
  - "5.1"
  - "4.2"
  - "0.12"
  - "0.10"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
